# Generated by Django 3.2.9 on 2021-12-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_auto_20211222_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='transaction_id',
            field=models.CharField(help_text='Enter transaction id here, transaction id will be provided by your service provider i.e EasyPaisa provide you through sms over a successful transaction', max_length=1000, unique=True),
        ),
    ]
